# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Barefoot Linguist
tagline:
url:              http://barefootlinguist.com
paginate:         30
baseurl:          /
author:
  name:           Jenia Gutova
  url:            http://barefootlinguist.com
  email:          jeniaa@gmail.com

sass:
  style:          compressed
